version: "3"

services:
  room:
    build:
      dockerfile: ./docker/service.Dockerfile
      context: .
      args:
        SERVICE: room
    container_name: room 
    extra_hosts:
      - postgres:172.16.16.3
    ports:
        - "3550:3550"
        - "8080:8080"
    volumes:
        - ./config/room.yaml:/home/app/config.yaml
    networks:
      chclone:
        ipv4_address: 172.16.16.2
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=chclone
        - POSTGRES_PASSWORD=chclone
        - POSTGRES_DB=chclone
        - POSTGRES_PORT=5432
    volumes:
      - db:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    privileged: false
    networks:
      chclone:
        ipv4_address: 172.16.16.3

        #ion-sfu:
        #  image: pionwebrtc/ion-sfu:latest-allrpc
        #  container_name: ion-sfu
        #  environment:
        #    - gaddr=0.0.0.0:50052
        #    - jaddr=0.0.0.0:7000
        #  ports:
        #    - "7000:7000"
        #    - "50052:50052"
        #    - "5000-5200:5000-5200/udp"
        #  networks:
        #    chclone:
        #      ipv4_address: 172.16.16.3

volumes:
  db:

networks:
  chclone:
    ipam:
      driver: default
      config:
        - subnet: "172.16.16.0/16"
